syntax = "proto3";
package atomone.mymodule.v1;

import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "cosmos_proto/cosmos.proto";

option go_package = "github.com/atomone-hub/atomone/x/mymodule/types";

// Params defines the parameters for the x/mymodule module.
message Params {
  // Enables mymodule or not
  bool mymodule_disabled = 1;

}

// Params defines the parameters for the x/mymodule module.
message SecureMessage {
  google.protobuf.Timestamp submit_time = 1 [ (gogoproto.stdtime) = true ];
  option (gogoproto.equal)           = false;
  option (gogoproto.goproto_getters) = false;

  bytes   encrypted_from_address          = 2;
  string   to_address                      = 3 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  bytes   encrypted_text                  = 4;
  string   signature                       = 5;
}

message SecureMessages {
  repeated SecureMessage msgs = 1;
}
